# Configurações básicas do site
title: "Jacques - Testing Blog"
description: "Blog sobre desenvolvimento, testes, tecnologia, IA e programação."
url: "https://juniorschmitz.github.io"
baseurl: ""

# Configurações do autor
author:
  name: "Jacques Schmitz Junior"
  email: "juniorschmitz9@gmail.com"
  bio: "QA Manager apaixonado por tecnologia e qualidade de software."
  avatar: "/assets/images/avatar.jpg"
  social:
    github: "juniorschmitz"
    linkedin: "https://www.linkedin.com/in/jacques-schmitz-junior/"

# Configurações de build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: America/Sao_Paulo

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Paginação
paginate: 6
paginate_path: "/page:num/"

# Configurações de SEO
lang: pt-BR
google_analytics: "SEU-ID-GOOGLE-ANALYTICS"

# Configurações de build
sass:
  sass_dir: _sass
  style: compressed

# Exclusões
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
